spring:
  datasource:
    xa:
      properties:
        useInformationSchema: true
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#    username: DREAM_BASKETBALL
#    password: DREAM_BASKETBALL1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dream_basketball
    username: root
    password: Aa52485248!@
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    enabled: true
    #??
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    #????
    suffix: .ftl
    template_update_delay: 0
    mvc:
      static-path-pattern: /static/**
      date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: localhost
    port: 6379
    database: 0 # 操作的是0号数据库
    jedis: #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 3s
    #??
#    template-loader-path: classpath:/templates/
server:
  port: 8088
mybatis-plus:
  #????xml????
  #config-location: classpath:mybatis-config.xml
  #??????? MyBatis Properties ???????????????????????????????????????ò???
  #configuration-properties: classpath:mybatis/config/properties
  #xml???????????????????????? Mapper ??????? XML ???????
  mapper-locations: classpath*:mybatis/*.xml
  #MyBatis ?????????·???????????????????????????????????·?????????
  type-aliases-package: com.dream.basketball.entity
  #?????????????????????????·??????????????????????
  type-aliases-super-type: java.lang.Object
  #????? ???·?????????????????????·????????????????????????????????????????????
  #type-enums-package: com.wongoing.sys.model
  #???????????xml??????????????????
#  check-config-location: true
  #SIMPLE?????????????????????????????????????????????????????REUSE??????????????????????BATCH????????????????????????????????
#  executor-type: REUSE
  configuration:
    #???????????????
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    # ???????????????????camel case????????????????????? A_COLUMN????????????? ?????? Java ?????? aColumn??????????? ?????????
#    map-underscore-to-camel-case: true
#    # ???????????????????????????????????????????????? true
#    cache-enabled: true
#    #??????
#    aggressive-lazy-loading: true
#    #none?????????????? partial?????????? resultMap ?????????? full????????? resultMap ????????????
#    auto-mapping-behavior: partial
#    #none???????????? (????)warning???????????????????????? failing??????????????????????????????
#    auto-mapping-unknown-column-behavior: none
#    #???????????????????????? MyBatis ?????????????????????
#    call-setters-on-nulls: true   #??????resultType="map"????null?
#    #????????????sql????????????????????????????
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    #?????????????????????
#    multiple-result-sets-enabled: false
  global-config:
    db-config:
      update-strategy: IGNORED
#      #?????????????????true
#      table-underline: false
#      #id?????
#      id-type: ASSIGN_ID # ????ASSIGN_ID
#      #??????????????????????
#      capital-mode: false
#      #?????????(???????????)
#      logic-not-delete-value: 0 # ????????(???? 0)
#      #????????(???????????)
#      logic-delete-value: 1 # ?????????(???? 1)